### ISSUE TITLE
Broken images on settings form.

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/extlink#2]
![selection_004](https://cloud.githubusercontent.com/assets/1071483/20235404/d1ee1b6c-a85e-11e6-994e-f619dd45515e.png)

**Comment by olafgrabienski** [comment]
@herbdool I've just installed the External Links module for the first time, and I can't confirm the issue with broken images on the settings form on a 1.8.0 site. Is it still an issue on your site(s)?

**Comment by ghost** [comment]
[This commit](https://github.com/backdrop-contrib/extlink/commit/dd6860b8bfc895c749cef0416db858ea5ab22280) made some changes to these images, so this should be fixed now anyway.
