### ISSUE TITLE
Cleanup module files

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/extlink#3]
It looks like the files in this module could be cleaned up a bit, both for coding standards and ease-of-use:

- Move CSS and JS files into appropriate sub-directories
- Move images into an appropriate sub-directory
- Move tests into an appropriate sub-directory

**Comment by herbdool** [comment]
@BWPanda I think Nate would probably like it if someone adopted this module. Feel like cleaning it up?

**Comment by ghost** [comment]
Sure, I could give it a go. I've asked @quicksketch in Zulip if he'd allow me to be a co-maintainer for this project...

**Comment by ghost** [comment]
Here's an initial PR based on the points above: https://github.com/backdrop-contrib/extlink/pull/4

But I think there's more I can do to cleanup the code. More commits to come...

**Comment by ghost** [comment]
Made another commit that does some more cleanup of the code.

**Comment by quicksketch** [comment]
@BWPanda pinged me on Zulip to request added being added as a maintainer. Totally fine by me :+1:

**Comment by ghost** [comment]
Merged, thanks!
