### ISSUE TITLE
Readme Improvements

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/extlink#5]
I'm about to submit a simple PR that adds a little more info to the README

**Comment by stpaultim** [comment]
I was looking for a module that would open all external links in a new tab/window and it was not clear from the README that this module does that. So, I'm submitting a simple PR that adds a little more description to the README. 

It also mentioned the ability to add a pop-up warning that a user is clicking a link that leads to another site. I think this is worth mentioning in the README. 

See attached PR

Please, feel free to make whatever edits you like to my PR.

**Comment by ghost** [comment]
@stpaultim I updated the PR to try and convey the range of options this module has. Previously it seemed to focus mainly on the icons it allows you to add. But now hopefully it better shows all the options equally. See what you think.

**Comment by stpaultim** [comment]
Thanks @BWPanda. Good edits and huge improvement in explaining what the moduel actually does. 

Works for Me!

**Comment by ghost** [comment]
Thanks, merged.
