### ISSUE TITLE
Catch up to Drupal 7 version

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/extlink#7]
I was just comparing this module to the D7 version and it looks like there may be some relevant commits that would be good to pull over to this module.

**Comment by laryn** [comment]
@quicksketch I tried to merge all commits from D7 in the linked PR. It could stand another round of testing, I'm sure...

**Comment by herbdool** [comment]
@laryn technically the bug squad can't merge this since it might include non-bug fixes, but perhaps you'd be willing to be a co-maintainer of this?

**Comment by laryn** [comment]
@herbdool I've asked here: https://github.com/backdrop-contrib/extlink/issues/11
